---
driver:
  name: terraform

provisioner:
  name: terraform

platforms:
  - name: ubuntu
 
verifier:
  name: terraform
  systems:
    - name: default
      backend: ssh
      user: ubuntu
      hosts:
        - 52.206.96.214
      key_files:
        - ~/.ssh/id_rsa
      controls:
      - check_pkg

suites:
  - name: default